[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/providers"
  to = "/.netlify/functions/providers"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://polymovies.onrender.com/api/:splat"
  status = 200
  force = true
