[functions]
  directory = "netlify/functions"
  included_files = ["manifest.json"]

[[redirects]]
  from = "/api/providers"
  to = "/.netlify/functions/providers"
  status = 200
  force = true

[[redirects]]
  from = "/env.js"
  to = "/.netlify/functions/env"
  status = 200
  force = true

[[redirects]]
  from = "/movie/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://polymovies.onrender.com/api/:splat"
  status = 200
  force = true
